### ISSUE TITLE
cellinfo

### ISSUE THREAD

**Issue by elyesjabri** [codebakery/codebakery-plugin-cellinfo#1]
please more details of the two Methods and how to use them 
thnx in advance

**Comment by dgladkov** [comment]
Hi!

Please note that the plugin supports Android only, iOS does not provide APIs for gathering cell information.

You can use it like this:

``` javascript
CellInfo.getNeighboringCellInfo(
  function(cellInfo) {
    console.log(cellInfo);
  }, 
  function(error) {
    console.error(cellInfo);
  }
);
```

This example should print cellInfo object with the structure described here: https://github.com/codebakery/codebakery-plugin-cellinfo#cellinfodata-object

**Comment by dgladkov** [comment]
Added function arguments to the README

**Comment by elyesjabri** [comment]
the cordova app is crashing under android

```
onDeviceReady: function() {
    console.log("Ready");
    app.testzone = document.getElementById("test-zone");
    //cellinfo
    CellInfo.getNeighboringCellInfo(
```

  function(cellInfo) {
    console.log(cellInfo);
  },
  function(error) {
    console.error(cellInfo);
  });

},

2016-04-13 13:39 GMT+02:00 Dmitry Gladkov notifications@github.com:

**Comment by elyesjabri** [comment]
solved permission problem thx any way

2016-04-14 8:04 GMT+02:00 med elyes jabri elyes.jabri@gmail.com:
